export type TemplateCategory =
  | 'all'
  | 'style'
  | 'promo'
  | 'vip'
  | 'campaign'
  | 'holiday'
  | 'social'
  | 'trust'
  | 'business'

export interface VisualTemplate {
  id: string
  title: string
  feeling: string
  category: TemplateCategory
  applicability: string
  positivePrompt: string
  negativePrompt: string
  paramAdvice: string
  defaultAspect: '1:1' | '4:5' | '3:4' | '16:9' | '9:16'
  badge?: string
  gradient: string
  tags: string[]
  previewUrl?: string
}

export const CATEGORIES: { key: TemplateCategory; label: string; icon: string; desc: string }[] = [
  { key: 'all',      label: '全部風格',   icon: 'Sparkles', desc: '探索所有視覺風格與宣傳模板' },
  { key: 'style',    label: '視覺風格',   icon: 'Palette',  desc: '黏土、微縮、3D、普普、線稿、霓虹等藝術質感' },
  { key: 'promo',    label: '促銷折扣',   icon: 'Tag',      desc: '主檔大促、%折扣、多件折、免運、限時搶購' },
  { key: 'vip',      label: '會員與VIP',  icon: 'Crown',    desc: '會員日、VIP尊榮、早鳥提前搶、新品預售' },
  { key: 'campaign', label: '檔期大促',   icon: 'Zap',      desc: '黑五、雙12、年中慶、發薪日、週年慶、新店開幕' },
  { key: 'holiday',  label: '節慶節日',   icon: 'Gift',     desc: '農曆春節、中秋、聖誕、情人節、母親節、元旦' },
  { key: 'social',   label: '社群互動',   icon: 'MessageSquare', desc: '投票、問答卡、該做與不該做、迷思破解' },
  { key: 'trust',    label: '信任證言',   icon: 'ShieldCheck',   desc: '買家好評、星級評分、媒體露出、得獎標章' },
  { key: 'business', label: '商業公告',   icon: 'Megaphone', desc: '即將上市、門市搬遷、徵才、加盟招募、聯名' },
]

export const VISUAL_TEMPLATES: VisualTemplate[] = [
  // ── 視覺風格篇（20 種）─────────────────────────────────────────
  {
    id: 'claymodel',
    title: '黏土玩偶風',
    feeling: '立體童趣・軟萌擬人・溫暖光感',
    category: 'style',
    applicability: '商品擬人化、品牌吉祥物、IG 貼文與精選封面',
    positivePrompt: 'clay model style, soft studio lighting, pure background, toy-like texture, rounded shapes, high saturation, cute proportions, product as a character',
    negativePrompt: 'photorealistic, noisy, lowres, deformed, extra fingers, text watermark',
    paramAdvice: '比例 1:1 或 4:5；細節強度中等；柔和陰影',
    defaultAspect: '1:1',
    badge: '熱門風格',
    gradient: 'from-amber-400 via-orange-400 to-rose-400',
    tags: ['商品擬人', '可愛軟萌', '黏土立體', 'IG封面'],
    previewUrl: '/images/templates/claymodel.jpg',
  },
  {
    id: 'miniature',
    title: '微縮模型景深',
    feeling: '景深移軸・微型世界・精巧微距',
    category: 'style',
    applicability: '門市陳列感、微縮世界場景創意、文創商品',
    positivePrompt: 'miniature diorama, tilt-shift blur, macro photography, small scale props, clean backdrop, shallow depth of field',
    negativePrompt: 'blurry subject, over-sharpened edges, cluttered background, distorted',
    paramAdvice: '景深明顯、背景強烈虛化；比例 3:4 或 1:1',
    defaultAspect: '3:4',
    badge: '微距創意',
    gradient: 'from-emerald-400 via-teal-500 to-cyan-600',
    tags: ['移軸攝影', '微型模型', '小人國視角', '門市場景'],
    previewUrl: '/images/templates/miniature.jpg',
  },
  {
    id: 'popart',
    title: '普普藝術插畫',
    feeling: '高對比色塊・半色調網點・海報張力',
    category: 'style',
    applicability: '促銷檔期、節慶快閃、潮牌聯名、震撼視覺',
    positivePrompt: 'pop art, bold colors, halftone dots, high contrast, graphic outlines, poster style, vibrant retro',
    negativePrompt: 'muddy colors, low contrast, photorealistic shading, washed out',
    paramAdvice: '飽和度高、對比強烈；適合海報尺寸 3:4 或 2:3',
    defaultAspect: '3:4',
    badge: '視覺張力',
    gradient: 'from-pink-500 via-rose-500 to-yellow-400',
    tags: ['高飽和', '網點色塊', '波普風', '活動海報'],
    previewUrl: '/images/templates/popart.jpg',
  },
  {
    id: 'inkline',
    title: '俐落線稿插畫',
    feeling: '乾淨輪廓・向量線條・純白極簡',
    category: 'style',
    applicability: '教學圖、步驟說明、產品結構、包裝與杯套插圖',
    positivePrompt: 'ink line drawing, clean contours, minimal shading, vector-like, white background, precise linework',
    negativePrompt: 'heavy shadows, photorealistic texture, noise, messy lines, gradients',
    paramAdvice: '線寬一致、背景純白；極佳去背友好度',
    defaultAspect: '1:1',
    gradient: 'from-slate-600 via-gray-700 to-zinc-800',
    tags: ['純白極簡', '向量線稿', '步驟教學', '包裝手繪'],
    previewUrl: '/images/templates/inkline.jpg',
  },
  {
    id: '3drender',
    title: '擬真 3D 渲染',
    feeling: '柔和棚燈・細膩倒影・旗艦電商質感',
    category: 'style',
    applicability: '電商首圖、型錄封面、官網 Hero Banner、高端產品展示',
    positivePrompt: 'photorealistic 3D render, studio softbox lighting, subtle reflections, clean shadow, product on seamless backdrop, octane render, 8k',
    negativePrompt: 'cartoonish, lowres, plastic shine, harsh shadows, noisy, blurry',
    paramAdvice: '高光柔和、陰影自然；比例 1:1 或 16:9',
    defaultAspect: '1:1',
    badge: '電商必備',
    gradient: 'from-blue-500 via-indigo-600 to-violet-700',
    tags: ['電商首圖', '攝影棚燈', '精緻倒影', '官網主視覺'],
    previewUrl: '/images/templates/3drender.jpg',
  },
  {
    id: 'pixelart',
    title: '復古像素風',
    feeling: '8-bit/16-bit・方塊美學・懷舊遊戲感',
    category: 'style',
    applicability: '遊戲化行銷活動、年輕潮流受眾、趣味積分互動',
    positivePrompt: 'pixel art, 8-bit/16-bit style, blocky shapes, limited palette, retro game aesthetic, clean pixel grid',
    negativePrompt: 'anti-aliasing, smooth gradients, photorealistic, blurry, highres 3D',
    paramAdvice: '像素顆粒清晰、色彩受限復古；1:1 最佳',
    defaultAspect: '1:1',
    gradient: 'from-purple-500 via-indigo-500 to-pink-500',
    tags: ['復古像素', '8-bit', '街機遊戲', '年輕潮流'],
    previewUrl: '/images/templates/pixelart.jpg',
  },
  {
    id: 'neoncyber',
    title: '霓虹賽博風',
    feeling: '暗黑夜色・邊緣強發光・青紅對比',
    category: 'style',
    applicability: '夜間經濟、酒吧/茶飲夜間檔、音樂派對、快閃店封面',
    positivePrompt: 'neon cyberpunk, glowing edges, dark background, magenta and cyan palette, volumetric light, moody atmosphere, futuristic city glow',
    negativePrompt: 'washed out colors, daylight, flat lighting, sunny, pastels',
    paramAdvice: '深色背景＋強烈冷暖霓虹光；9:16 短影音封面超吸睛',
    defaultAspect: '9:16',
    badge: '夜間檔期',
    gradient: 'from-fuchsia-600 via-purple-700 to-cyan-500',
    tags: ['霓虹發光', '賽博龐克', '夜店酒吧', '短影音封面'],
    previewUrl: '/images/templates/neoncyber.jpg',
  },
  {
    id: 'pastelsoft',
    title: '柔粉奶油調',
    feeling: '低飽和粉嫩・柔和乳霜感・夢幻氛圍',
    category: 'style',
    applicability: '美妝保養、甜點烘焙、下午茶、女性目標受眾',
    positivePrompt: 'pastel color palette, soft creamy lighting, gentle shadows, dreamy atmosphere, minimal props, warm aesthetic, high key lighting',
    negativePrompt: 'harsh contrast, saturated neon, clutter, dark shadows, gritty',
    paramAdvice: '低對比、高明度、溫和淺色；4:5 或 1:1',
    defaultAspect: '4:5',
    gradient: 'from-rose-300 via-pink-200 to-amber-100',
    tags: ['奶油粉嫩', '甜點下午茶', '女性受眾', '高明度溫潤'],
    previewUrl: '/images/templates/pastelsoft.jpg',
  },
  {
    id: 'retro90s',
    title: '90 復古懷舊',
    feeling: 'VHS 膠卷雜訊・褪色膠片・幾何字體留白',
    category: 'style',
    applicability: '懷舊復刻行銷、週年經典重現、品牌故事',
    positivePrompt: '1990s retro aesthetic, VHS grain, faded colors, nostalgic film tone, geometric patterns, bold typography space',
    negativePrompt: 'ultra clean, modern minimal, HDR, digital crisp, oversaturated',
    paramAdvice: '適度底片顆粒與微色偏；保留大標題文字排版空間',
    defaultAspect: '4:5',
    gradient: 'from-amber-600 via-orange-600 to-red-700',
    tags: ['VHS膠卷', '90年代', '經典復刻', '懷舊情感'],
    previewUrl: '/images/templates/retro90s.jpg',
  },
  {
    id: 'magazine',
    title: '高端雜誌封面',
    feeling: '高端社論光・大膽主標留白・時尚肖像',
    category: 'style',
    applicability: '品牌故事、人物專訪、主廚推薦、年度旗艦宣傳',
    positivePrompt: 'magazine cover layout, bold headline area, clean portrait, editorial lighting, masthead space, high fashion editorial, sharp details',
    negativePrompt: 'busy background, low resolution, watermark, amateur, snapshot',
    paramAdvice: '頂部預留大標題區；3:4 或 A4 比例',
    defaultAspect: '3:4',
    badge: '高端質感',
    gradient: 'from-neutral-800 via-stone-700 to-zinc-900',
    tags: ['時尚雜誌', '人物專訪', '高端質感', '社論光影'],
    previewUrl: '/images/templates/magazine.jpg',
  },
  {
    id: 'mockupbox',
    title: '擬真包裝 Mockup',
    feeling: '真實光影投影・俐落無縫背景・品牌貼圖區',
    category: 'style',
    applicability: '新品包裝預告、通路提報提案、禮盒外觀展示',
    positivePrompt: 'product mockup, box or bottle on clean surface, realistic shadows, subtle reflections, brandable area, professional studio display',
    negativePrompt: 'distorted perspective, lowres, cluttered props, bad labels',
    paramAdvice: '透視正確、陰影自然；正面或 45 度微俯視',
    defaultAspect: '1:1',
    gradient: 'from-slate-400 via-zinc-400 to-stone-500',
    tags: ['包裝打樣', '產品禮盒', '通路提案', '透視擬真'],
    previewUrl: '/images/templates/mockupbox.jpg',
  },
  {
    id: 'stopmotion',
    title: '定格動畫手工感',
    feeling: '手工微頓感・溫暖生活感・俏皮玩味',
    category: 'style',
    applicability: 'Reels / TikTok 短影片封面、趣味社群互動、手作體驗',
    positivePrompt: 'stop motion aesthetic, slightly stepped motion blur, handcrafted look, playful props, warm light, plasticine or papercraft texture',
    negativePrompt: 'overly smooth CGI, motion-blur smear, noisy, digital flat',
    paramAdvice: '強調材質手工質感與暖色調；9:16 短影音專用',
    defaultAspect: '9:16',
    gradient: 'from-yellow-400 via-amber-500 to-orange-500',
    tags: ['定格手作', '短影音封面', '黏土紙雕', '生動活潑'],
    previewUrl: '/images/templates/stopmotion.jpg',
  },
  {
    id: 'infographic',
    title: '現代資訊圖表',
    feeling: '簡潔圖標・數據視覺化・大面積清爽留白',
    category: 'style',
    applicability: '營養成分、成分解析、製程步驟、教育型專業知識貼文',
    positivePrompt: 'infographic style, clear icons, clean charts, ample white space, readable labels, modern UI graphics, structured layout',
    negativePrompt: 'cluttered, tiny unreadable text, low contrast, messy diagrams',
    paramAdvice: '保留圖表與數字區域；1:1 或 4:5 貼文比例',
    defaultAspect: '1:1',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-600',
    tags: ['數據圖表', '知識圖卡', '成分拆解', '高清晰度'],
    previewUrl: '/images/templates/infographic.jpg',
  },
  {
    id: 'memesticker',
    title: '趣味迷因貼紙',
    feeling: '粗白邊輪廓・表情張力・極簡乾淨背景',
    category: 'style',
    applicability: '社群互動引流、貼圖包製作、留言區互動、年輕受眾共鳴',
    positivePrompt: 'meme sticker style, thick outline, white border, expressive face, simple background, die-cut sticker look, bold graphic illustration',
    negativePrompt: 'photorealistic, complex scene, small details, muddy background',
    paramAdvice: '邊框俐落明顯、去背友好；1:1 貼紙尺寸',
    defaultAspect: '1:1',
    gradient: 'from-lime-400 via-emerald-400 to-teal-500',
    tags: ['迷因白邊', '社群互動', '貼圖表情', '幽默吸睛'],
    previewUrl: '/images/templates/memesticker.jpg',
  },
  {
    id: 'luxgold',
    title: '奢華黑金極致',
    feeling: '黑金金屬高光・暗黑深邃・尊爵高級感',
    category: 'style',
    applicability: '高單價商品、限量款發售、VIP 專屬尊榮獻禮',
    positivePrompt: 'luxury gold and black, metallic highlights, dramatic lighting, elegant serif space, premium feel, dark obsidian backdrop, golden shimmer',
    negativePrompt: 'cheap plastic look, flat light, clutter, loud bright colors',
    paramAdvice: '精緻金屬拉絲與高光反射；3:4 或 16:9',
    defaultAspect: '3:4',
    badge: '尊榮頂級',
    gradient: 'from-yellow-600 via-amber-700 to-stone-900',
    tags: ['黑金奢華', '尊爵VIP', '金屬高光', '高客單價'],
    previewUrl: '/images/templates/luxgold.jpg',
  },
  {
    id: 'flatlay',
    title: '俯拍平鋪陳列',
    feeling: '上帝視角俯視・整齊幾何排列・自然柔和光',
    category: 'style',
    applicability: '電商開箱文、套組全家福銷售、食材用料一字排開',
    positivePrompt: 'flat lay photography, top-down view, organized composition, neutral backdrop, soft shadows, knolling arrangement, natural lighting',
    negativePrompt: 'angled view, messy arrangement, harsh shadows, perspective distortion',
    paramAdvice: '90 度直角俯拍、留白呼吸感足夠；1:1 或 4:5',
    defaultAspect: '1:1',
    gradient: 'from-orange-200 via-amber-200 to-stone-200',
    tags: ['俯拍平鋪', '全套開箱', '食材用料', '整齊排列'],
    previewUrl: '/images/templates/flatlay.jpg',
  },
  {
    id: 'cinematic',
    title: '電影感劇照',
    feeling: '故事氛圍・精湛調色・淺景深戲劇張力',
    category: 'style',
    applicability: '品牌形象廣告、主理人理念、品牌微電影視覺',
    positivePrompt: 'cinematic still, dramatic lighting, anamorphic lens flare, professional color grading, shallow depth of field, story mood, 35mm film',
    negativePrompt: 'flat lighting, snapshot look, overexposed, generic stock photo',
    paramAdvice: '色調統一、光影有層次；16:9 橫幅最具電影感',
    defaultAspect: '16:9',
    gradient: 'from-indigo-900 via-slate-800 to-zinc-900',
    tags: ['電影劇照', '光影調色', '品牌形象', '戲劇氛圍'],
    previewUrl: '/images/templates/cinematic.jpg',
  },
  {
    id: 'uadvertising',
    title: '真實生活 UGC 風',
    feeling: '生活隨拍感・自然採光・零距離親切感',
    category: 'style',
    applicability: '廣告投放素材、降低廣告防備心、素人口碑推薦',
    positivePrompt: 'UGC ad style, smartphone photo look, natural light, casual composition, authentic vibe, realistic everyday scenario, real customer perspective',
    negativePrompt: 'over-produced studio look, heavy retouch, fake 3D, stock model pose',
    paramAdvice: '保留生活日常溫度與自然光線；4:5 或 9:16',
    defaultAspect: '4:5',
    badge: '高點擊投放',
    gradient: 'from-emerald-300 via-teal-400 to-sky-400',
    tags: ['真實UGC', '手機隨手拍', '素人視角', '低廣告感'],
    previewUrl: '/images/templates/uadvertising.jpg',
  },
  {
    id: 'beforeafter',
    title: '前後對比切割',
    feeling: '雙畫面分割・角度嚴格對齊・效果顯著反差',
    category: 'style',
    applicability: '改造前後對照、效果實證、修復/保養前後奇蹟變化',
    positivePrompt: 'before after split composition, consistent angle and lighting, clear divider, label areas, dramatic contrast between states',
    negativePrompt: 'mismatched perspective, different color temp, clutter, unaligned frames',
    paramAdvice: '左右或上下中線分割、左右留標籤文字區；1:1 或 4:5',
    defaultAspect: '1:1',
    gradient: 'from-violet-400 via-purple-500 to-indigo-600',
    tags: ['前後對比', '改造效果', '雙拼分割', '實證反差'],
    previewUrl: '/images/templates/beforeafter.jpg',
  },
  {
    id: 'seasonal',
    title: '節慶檔期氛圍',
    feeling: '節慶專屬道具・熱鬧慶祝感・濃厚節日色調',
    category: 'style',
    applicability: '春節、中秋、聖誕、黑五等特定節日專屬視覺',
    positivePrompt: 'seasonal theme elements, festive colors, decorative holiday props, celebratory mood, seasonal foliage and ambient lights, warm celebration',
    negativePrompt: 'off-theme props, clashing colors, clutter, somber atmosphere',
    paramAdvice: '依節日搭配主色調；1:1 或 4:5',
    defaultAspect: '1:1',
    gradient: 'from-red-500 via-rose-500 to-amber-400',
    tags: ['節日氛圍', '應景道具', '節慶特刊', '歡慶裝飾'],
    previewUrl: '/images/templates/seasonal.jpg',
  },

  // ── 促銷與優惠篇（15 種）────────────────────────────────────────
  {
    id: 'herooffer',
    title: '主檔大促主視覺',
    feeling: '超大折扣數字・商品焦點聚焦・CTA 購買按鈕留白',
    category: 'promo',
    applicability: '首頁 Banner、促銷主視覺、檔期核心吸睛圖',
    positivePrompt: 'hero offer visual, big discount number focal point, prominent product focus, CTA button space, clean background, high conversion commercial layout',
    negativePrompt: 'tiny text, cluttered, low contrast, messy elements, confusing layout',
    paramAdvice: '16:9 或 21:9；數字超大、留清楚按鈕點擊區',
    defaultAspect: '16:9',
    badge: '超強轉化',
    gradient: 'from-red-600 via-rose-600 to-orange-500',
    tags: ['主檔促銷', '大折扣數字', '首頁Banner', '超強點擊'],
    previewUrl: '/images/templates/herooffer.jpg',
  },
  {
    id: 'percentoff',
    title: '折扣百分比徽章',
    feeling: '醒目「%」角標・大膽品牌色・極簡俐落',
    category: 'promo',
    applicability: '全站/分類折扣、會員日特惠、快速傳遞降價幅度',
    positivePrompt: 'percent off badge, large prominent "%" symbol, short subtext area, bold brand colors, minimal props, high contrast promotion card',
    negativePrompt: 'tiny text, cluttered, low contrast, washed out colors',
    paramAdvice: '1:1 或 4:5；「%」字體最大最突出',
    defaultAspect: '1:1',
    gradient: 'from-rose-500 via-pink-600 to-purple-600',
    tags: ['折數角標', '百分比% ', '全店折扣', '簡約醒目'],
    previewUrl: '/images/templates/percentoff.jpg',
  },
  {
    id: 'buymore',
    title: '多件多折省錢卡',
    feeling: '階梯式價格牌・省錢試算・一眼看懂多買划算',
    category: 'promo',
    applicability: '第 2 件 6 折、3 入 599、套組加購衝高客單價',
    positivePrompt: 'buy more save more promotional graphic, multiple products lineup, tiered price labels, clear savings math, action-driven CTA',
    negativePrompt: 'tiny text, cluttered, unclear savings, chaotic stacking',
    paramAdvice: '4:5 或 1:1；「省多少錢」必須一眼看透',
    defaultAspect: '4:5',
    badge: '拉高客單',
    gradient: 'from-amber-500 via-orange-500 to-red-500',
    tags: ['第二件半價', '多入優惠', '衝客單價', '省錢算式'],
    previewUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'freeship',
    title: '滿額免運卡',
    feeling: '小貨車徽章・醒目門檻金額・極簡乾淨背景',
    category: 'promo',
    applicability: '電商促購、跨店滿額免運、結帳前最後湊單引導',
    positivePrompt: 'free shipping promotion badge, delivery truck icon, prominent threshold text banner, clean uncluttered background, delivery theme',
    negativePrompt: 'tiny text, cluttered, low contrast, complicated background',
    paramAdvice: '1:1 或 4:5；免運門檻金額要醒目大號字',
    defaultAspect: '1:1',
    gradient: 'from-blue-600 via-cyan-600 to-teal-500',
    tags: ['滿額免運', '外送專案', '湊單神卡', '宅配到府'],
    previewUrl: '/images/templates/freeship.jpg',
  },
  {
    id: 'giftwithpurchase',
    title: '滿額加碼贈禮',
    feeling: '主商品＋精緻贈品同框・「FREE」標章・數量有限提醒',
    category: 'promo',
    applicability: '滿額贈品、限量加碼禮、高單價推波助瀾',
    positivePrompt: 'gift with purchase showcase, hero product alongside exclusive gift, prominent "Free" label badge, while-stocks-last hint ribbon, premium composition',
    negativePrompt: 'tiny text, cluttered, unclear offer, hidden gift item',
    paramAdvice: '4:5 或 1:1；贈品與主品大小比例明確',
    defaultAspect: '4:5',
    gradient: 'from-purple-600 via-pink-600 to-rose-500',
    tags: ['滿額好禮', '送完為止', '主贈同框', '限量加碼'],
    previewUrl: '/images/templates/giftwithpurchase.jpg',
  },
  {
    id: 'limitedtime',
    title: '限時倒數急迫感',
    feeling: '時鐘/倒數計時圖標・截止日特大・強烈急迫感',
    category: 'promo',
    applicability: '限時特賣、閃購快閃、今日最後搶購倒數',
    positivePrompt: 'limited time offer poster, prominent clock and timer icon, bold deadline text, urgent high-energy CTA, bold contrast, countdown atmosphere',
    negativePrompt: 'tiny text, cluttered, low urgency, dull sleepy colors',
    paramAdvice: '4:5 或 1:1；截止時間字體最大',
    defaultAspect: '4:5',
    badge: '急迫搶購',
    gradient: 'from-red-500 via-orange-500 to-amber-500',
    tags: ['限時倒數', '閃購快閃', '急迫催購', '最後截止'],
    previewUrl: '/images/templates/limitedtime.jpg',
  },
  {
    id: 'todayonly',
    title: '今日限定破盤',
    feeling: '大膽當日日期・破盤特惠折扣・促購 CTA',
    category: 'promo',
    applicability: '單日限定促銷、直播專屬特惠、店休日/特別日專屬',
    positivePrompt: 'today only exclusive deal badge, bold prominent date stamp, super bold discount rate, instant purchase CTA, punchy vibrant graphics',
    negativePrompt: 'tiny text, cluttered, low contrast, dated layout',
    paramAdvice: '1:1 或 4:5；日期與超低價格最醒目',
    defaultAspect: '1:1',
    gradient: 'from-amber-400 via-rose-500 to-red-600',
    tags: ['本日限定', '直播專屬', '破盤特賣', '秒殺快搶'],
    previewUrl: '/images/templates/todayonly.jpg',
  },
  {
    id: 'priceanchor',
    title: '價格錨點劃線對比',
    feeling: '原價俐落劃線・大號超值新價・超值心理暗示',
    category: 'promo',
    applicability: '原價與特價對比、直降優惠、促銷商品卡',
    positivePrompt: 'price anchor visual, old price strikethrough, huge prominent new price, concise value proposition headline, clean e-commerce banner',
    negativePrompt: 'tiny text, cluttered, confusing math, illegible strikethrough',
    paramAdvice: '1:1 或 4:5；劃線原價小、新特價超大號字',
    defaultAspect: '1:1',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-700',
    tags: ['劃線原價', '特價對比', '價格錨點', '心理省錢'],
    previewUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bundlecompare',
    title: '超值套組省錢對照',
    feeling: '單買 vs 套組・省下金額特大・組合划算感',
    category: 'promo',
    applicability: '單買與組合套組比較、A 套組 vs B 套組、全家享用組',
    positivePrompt: 'bundle comparison graphic, what is included layout, total calculated value, huge savings callout, organized product grouping',
    negativePrompt: 'tiny text, cluttered, unclear savings, messy props',
    paramAdvice: '4:5 或 3:4；強調「立省金額」最吸睛',
    defaultAspect: '4:5',
    gradient: 'from-indigo-500 via-purple-600 to-pink-500',
    tags: ['超值組合', '單買比對', '套組特惠', '省錢亮點'],
    previewUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'upsell',
    title: '結帳頁加購驚喜',
    feeling: '加購專屬甜甜價・小巧附屬品・順手帶一件',
    category: 'promo',
    applicability: '購物車結帳加購、門市臨櫃加購、升級優惠',
    positivePrompt: 'upsell offer card, featured add-on product, special discounted add-on price tag, enticing quick-add CTA button, clean background',
    negativePrompt: 'tiny text, cluttered, low contrast, dominant over main item',
    paramAdvice: '4:5 或 1:1；加購超值感清楚',
    defaultAspect: '1:1',
    gradient: 'from-teal-400 via-cyan-500 to-blue-600',
    tags: ['臨櫃加購', '加價購', '順手帶一件', '甜甜加購價'],
    previewUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'crosssell',
    title: '絕佳搭配推薦',
    feeling: '2~3 件默契組合・「絕配組合」提示・情境感',
    category: 'promo',
    applicability: '甜點配茶飲、主餐配小食、相關週邊推薦',
    positivePrompt: 'cross-sell matching set, 2-3 harmonious products, pairs well with message tag, stylish coordinated tabletop layout',
    negativePrompt: 'tiny text, cluttered, mismatched items, chaotic background',
    paramAdvice: '4:5 或 1:1；擺設自然合理有默契',
    defaultAspect: '4:5',
    gradient: 'from-amber-300 via-orange-400 to-rose-400',
    tags: ['絕佳搭配', '下午茶套裝', '關聯推薦', '情境同框'],
    previewUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'abandonedcart',
    title: '購物車挽回專屬碼',
    feeling: '暖心提醒・額外專屬小驚喜・臨門一腳下單',
    category: 'promo',
    applicability: '未結帳提醒、投放再行銷、專屬免運優惠碼',
    positivePrompt: 'abandoned cart recovery visual, clean product thumbnail, special incentive discount code, friendly gentle CTA, warm inviting background',
    negativePrompt: 'tiny text, cluttered, pushy aggressive tone, loud harsh colors',
    paramAdvice: '4:5 或 1:1；優惠誘因一句話點題',
    defaultAspect: '1:1',
    gradient: 'from-violet-500 via-fuchsia-500 to-pink-500',
    tags: ['購物車挽回', '未結帳提醒', '專屬折扣碼', '再行銷'],
    previewUrl: 'https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'winback',
    title: '沉睡老友喚醒卡',
    feeling: '好久不見溫馨思念・專屬回流禮・誠意滿滿',
    category: 'promo',
    applicability: '久未回購會員、沉睡顧客喚醒、重聚專屬禮遇',
    positivePrompt: 'customer winback greeting, heartfelt "We miss you" headline, exclusive welcome-back gift voucher, warm emotional brand feel',
    negativePrompt: 'tiny text, cluttered, generic corporate, cold sterile look',
    paramAdvice: '4:5 或 1:1；情感文案＋明確誘因',
    defaultAspect: '1:1',
    gradient: 'from-rose-400 via-pink-400 to-amber-300',
    tags: ['老客喚醒', '好久不見', '回購好禮', '專屬思念'],
    previewUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'referral',
    title: '好友推薦雙向獎勵',
    feeling: '兩人同享優惠・雙向推薦碼・好東西與好友分享',
    category: 'promo',
    applicability: '老帶新裂變活動、雙向購物金贈送、專屬邀請碼',
    positivePrompt: 'referral program invitation, clear give and get dual benefits, prominent referral code and QR placeholder, celebratory sharing mood',
    negativePrompt: 'tiny text, cluttered, complex convoluted rules, dull tone',
    paramAdvice: '4:5 或 1:1；雙向獎勵「你得我得」直觀清楚',
    defaultAspect: '1:1',
    gradient: 'from-cyan-400 via-teal-500 to-emerald-500',
    tags: ['好友推薦', '好康同享', '雙向購物金', '社群裂變'],
    previewUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lowstock',
    title: '庫存告急即將斷貨',
    feeling: '倒數進度條・剩餘最後現貨・真實稀缺感',
    category: 'promo',
    applicability: '製造稀缺感、促成猶豫顧客立即結帳、熱門款最後現貨',
    positivePrompt: 'low stock warning badge, visual stock progress bar, "Only X left" urgent label, action-driven purchase CTA, authentic scarcity',
    negativePrompt: 'tiny text, cluttered, fake over-dramatized look, tacky stickers',
    paramAdvice: '4:5 或 1:1；數量數字醒目真實',
    defaultAspect: '4:5',
    badge: '加速決策',
    gradient: 'from-orange-500 via-red-500 to-rose-600',
    tags: ['庫存告急', '最後現貨', '稀缺倒數', '猶豫必買'],
    previewUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
  },

  // ── 會員與 VIP 篇（6 種）────────────────────────────────────────
  {
    id: 'membersday',
    title: '會員專屬日尊享',
    feeling: '皇冠/金鑰匙圖標・會員專屬色調・專屬尊貴感',
    category: 'vip',
    applicability: '每月會員日、點數雙倍贈、會員專享特價商品',
    positivePrompt: 'members day exclusive visual, crown or key icon, privileged VIP badge, signature brand colors, elegant festive member benefits card',
    negativePrompt: 'tiny text, cluttered, cheap discount look, loud garish colors',
    paramAdvice: '4:5 或 3:4；專屬感與榮譽感強烈',
    defaultAspect: '4:5',
    badge: '會員專屬',
    gradient: 'from-purple-700 via-indigo-700 to-violet-900',
    tags: ['會員日', '專屬點數', '專屬折扣', '尊榮感'],
    previewUrl: '/images/templates/membersday.jpg',
  },
  {
    id: 'vipaccess',
    title: 'VIP 奢華私享通道',
    feeling: '奢華黑金・金屬高光・精緻無襯線留白・尊寵感',
    category: 'vip',
    applicability: 'VVIP 專屬私密預購、高客單限量款、VIP 先行入會',
    positivePrompt: 'VIP access exclusive card, elegant gold and black metallic accents, prestigious badge, minimal text, ultra premium luxury feel, private preview tone',
    negativePrompt: 'cheap noisy look, cluttered layout, low contrast, gaudy elements',
    paramAdvice: '4:5 或 3:4；文字極簡、質感極高',
    defaultAspect: '3:4',
    badge: '尊榮頂規',
    gradient: 'from-stone-900 via-amber-900 to-yellow-600',
    tags: ['黑金VIP', '私密通道', '高單價預購', '極致奢華'],
    previewUrl: '/images/templates/vipaccess.jpg',
  },
  {
    id: 'earlyaccess',
    title: '早鳥搶先特權',
    feeling: '月曆啟動圖標・起跑日期・品牌專屬精緻外框',
    category: 'vip',
    applicability: '黑五早鳥入場、新品上市前 48 小時開搶、課程早鳥價',
    positivePrompt: 'early access privilege badge, calendar start date icon, prominent opening time, clear CTA button, elegant branded border frame',
    negativePrompt: 'tiny text, cluttered, unclear launch date, chaotic badges',
    paramAdvice: '4:5 或 1:1；開始日期與早鳥專屬字樣最大',
    defaultAspect: '4:5',
    gradient: 'from-indigo-600 via-violet-600 to-pink-500',
    tags: ['早鳥開搶', '提前入場', '專屬特權', '搶先預約'],
    previewUrl: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'presale',
    title: '新品預售專屬',
    feeling: '預售標籤・預計出貨時間・定金/全款清楚交代',
    category: 'vip',
    applicability: '年度旗艦新品預購、募資專案、限量批次預訂',
    positivePrompt: 'presale tag visual, estimated shipping date banner, deposit or early-bird pricing details, clean confident e-commerce layout',
    negativePrompt: 'tiny text, cluttered, low contrast, unreadable shipping date',
    paramAdvice: '4:5 或 3:4；預計出貨日期清楚明確',
    defaultAspect: '4:5',
    gradient: 'from-blue-600 via-indigo-600 to-purple-600',
    tags: ['新品預售', '募資預訂', '預計出貨', '首批搶先'],
    previewUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'waitlist',
    title: '缺貨候補登記卡',
    feeling: '通知搖鈴圖標・簡潔表單提示・第一時間回歸通知',
    category: 'vip',
    applicability: '熱銷缺貨登記、限量款第二波候補、額滿課程候補',
    positivePrompt: 'waitlist registration card, notification bell icon, sleek input prompt hint, signature brand colors, reassuring customer service feel',
    negativePrompt: 'tiny text, cluttered, low contrast, panic tone',
    paramAdvice: '4:5 或 1:1；登記提示清楚友善',
    defaultAspect: '1:1',
    gradient: 'from-slate-700 via-indigo-800 to-slate-900',
    tags: ['補貨通知', '候補登記', '排隊提醒', '第一時間發信'],
    previewUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'restock',
    title: '熱銷補貨驚喜回歸',
    feeling: '補貨警報標章・商品焦點主圖・「Back in stock」',
    category: 'vip',
    applicability: '人氣缺貨品重新到貨、季節招牌限定復刻、熱門補貨',
    positivePrompt: 'restock alert banner, hero product center stage, bold "Back in stock" ribbon label, buy now CTA, celebratory restock aura',
    negativePrompt: 'tiny text, cluttered, low contrast, dull energy',
    paramAdvice: '1:1 或 4:5；補貨回歸標籤特大',
    defaultAspect: '1:1',
    badge: '熱賣回歸',
    gradient: 'from-emerald-500 via-teal-600 to-blue-600',
    tags: ['補貨到', '重磅回歸', '現貨到齊', '人氣爆品'],
    previewUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
  },

  // ── 檔期大促篇（8 種）────────────────────────────────────────
  {
    id: 'blackfriday',
    title: '黑五狂歡狂降',
    feeling: '黑黃高飽和撞色・特大折扣・最後搶購倒數',
    category: 'campaign',
    applicability: '黑色星期五、年度大檔、全年最低價狂歡',
    positivePrompt: 'Black Friday sale visual, bold dramatic black and neon yellow colors, super large discount callout, urgent countdown deadline, explosive commercial energy',
    negativePrompt: 'tiny text, cluttered, low urgency, pastel soft colors',
    paramAdvice: '4:5 或 1:1；黑底撞高飽和黃/紅最吸睛',
    defaultAspect: '4:5',
    badge: '全年最殺',
    gradient: 'from-black via-zinc-900 to-yellow-500',
    tags: ['黑色星期五', '全年最低', '黑黃撞色', '狂歡大促'],
    previewUrl: '/images/templates/blackfriday.jpg',
  },
  {
    id: 'cybermonday',
    title: '網一科技數碼大促',
    feeling: '科技感數碼光效・電商專屬特惠・線上狂歡',
    category: 'campaign',
    applicability: '網路星期一、電商線上獨賣、3C/數碼檔期',
    positivePrompt: 'Cyber Monday promotion, futuristic digital tech vibe, circuit glow highlights, huge discount percentage, online exclusive deal banner',
    negativePrompt: 'tiny text, cluttered, low contrast, offline retail props',
    paramAdvice: '1:1 或 4:5；線上限定提示要鮮明',
    defaultAspect: '1:1',
    gradient: 'from-cyan-600 via-blue-600 to-indigo-800',
    tags: ['網一促銷', '線上限定', '科技光感', '電商狂歡'],
    previewUrl: '/images/templates/cybermonday.jpg',
  },
  {
    id: '1212',
    title: '雙 12 年終盛典',
    feeling: '大數字 12.12・最後一波年末優惠・年末回饋',
    category: 'campaign',
    applicability: '雙 12 年末狂歡、年終最後清倉、跨年倒數預熱',
    positivePrompt: '12.12 year-end mega sale, gigantic "12.12" typography, festive year-end celebration sparks, final discount opportunity, urgent CTA',
    negativePrompt: 'tiny text, cluttered, low contrast, dull quiet tone',
    paramAdvice: '1:1 或 4:5；12.12 數字必須佔據視覺中心',
    defaultAspect: '1:1',
    gradient: 'from-red-600 via-orange-600 to-pink-600',
    tags: ['雙12', '年終大促', '最後檔期', '年末清倉'],
    previewUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '99',
    title: '99 超狂購物節',
    feeling: '超醒目 9.9 數字・均一價 99・震撼親民好康',
    category: 'campaign',
    applicability: '9/9 購物節、均一價 99 元促銷、秋季首波大促',
    positivePrompt: '9.9 shopping festival deal, huge bold "9.9" typography, punchy value-first headline, vibrant retail banner style, clear discount label',
    negativePrompt: 'tiny text, cluttered, low contrast, complicated background',
    paramAdvice: '1:1 或 4:5；9.9 數字超醒目突出',
    defaultAspect: '1:1',
    gradient: 'from-orange-500 via-amber-500 to-rose-500',
    tags: ['99購物節', '均一價99', '親民秒殺', '秋季大促'],
    previewUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'payday',
    title: '發薪日犒賞小確幸',
    feeling: '日曆薪水袋提示・犒賞自己・月中/月底小確幸',
    category: 'campaign',
    applicability: '每月 5 號/25 號發薪日促銷、小資犒賞好物、限時小確幸',
    positivePrompt: 'payday celebration sale, calendar pay check icon, treat yourself theme, cheerful shopping celebration, limited time payday discount code',
    negativePrompt: 'tiny text, cluttered, stress or work imagery, gloomy colors',
    paramAdvice: '4:5 或 1:1；發薪犒賞氛圍要歡樂放鬆',
    defaultAspect: '4:5',
    gradient: 'from-emerald-400 via-teal-500 to-cyan-600',
    tags: ['發薪日', '犒賞自己', '小資小確幸', '月初限時'],
    previewUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'midyear',
    title: '年中 618 狂歡大促',
    feeling: '年中最強檔・倒數狂歡・全店年中狂降',
    category: 'campaign',
    applicability: '618 年中慶、夏季年中清倉、上半年業績總爆發',
    positivePrompt: 'midyear mega sale event, bold 618 headline graphics, vibrant summer discount elements, deadline urgency, high conversion festival banner',
    negativePrompt: 'tiny text, cluttered, low contrast, winter holiday elements',
    paramAdvice: '4:5 或 1:1；618 檔期字體超強視覺',
    defaultAspect: '4:5',
    badge: '年中大檔',
    gradient: 'from-pink-600 via-rose-500 to-orange-400',
    tags: ['年中慶', '618大促', '夏季狂歡', '年中最強'],
    previewUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'anniversary',
    title: '品牌週年慶感恩獻禮',
    feeling: '醒目週年數字・週年專屬特惠・真摯感謝有你',
    category: 'campaign',
    applicability: '門市 1 週年/5 週年/10 週年慶、品牌生日月全館感恩',
    positivePrompt: 'brand anniversary celebration, prominent years count badge, golden confetti accents, special commemorative offer, thank-you gratitude banner',
    negativePrompt: 'tiny text, cluttered, low contrast, somber look',
    paramAdvice: '4:5 或 3:4；年數大字＋金色慶祝亮片',
    defaultAspect: '4:5',
    badge: '週年慶典',
    gradient: 'from-amber-400 via-yellow-500 to-rose-500',
    tags: ['週年慶', '週年回饋', '品牌生日', '感謝有你'],
    previewUrl: '/images/templates/anniversary.jpg',
  },
  {
    id: 'grandopening',
    title: '新店盛大開幕誌慶',
    feeling: '開幕日期與地點・排隊開幕好禮・地圖指引熱鬧感',
    category: 'campaign',
    applicability: '新門市開幕、新專櫃進駐、旗艦店首波亮相',
    positivePrompt: 'grand opening ceremony announcement, clear date and location banner, exciting opening giveaway teaser, cheerful ribbons, festive storefront celebration',
    negativePrompt: 'tiny text, cluttered, unclear location info, dull quiet scene',
    paramAdvice: '4:5 或 3:4；開幕日期與門市名稱層次清晰',
    defaultAspect: '4:5',
    badge: '新店開幕',
    gradient: 'from-red-600 via-rose-600 to-amber-500',
    tags: ['盛大開幕', '新店報到', '開幕排隊禮', '門市地址'],
    previewUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  },

  // ── 節慶節日篇（8 種）────────────────────────────────────────
  {
    id: 'lunarnewyear',
    title: '農曆新年新春賀歲',
    feeling: '喜慶紅金配色・春節燈籠柑橘・吉祥如意迎好年',
    category: 'holiday',
    applicability: '春節年菜/禮盒檔期、開工紅包抽獎、新年走春特惠',
    positivePrompt: 'Lunar New Year festive celebration, rich red and gold palette, oriental lanterns and citrus branches, auspicious blessing banner, prosperous luxury mood',
    negativePrompt: 'wrong cultural symbols, cluttered, low contrast, dull gray tones',
    paramAdvice: '4:5 或 1:1；紅金配色、吉祥話洗煉大氣',
    defaultAspect: '1:1',
    badge: '春節檔期',
    gradient: 'from-red-600 via-red-700 to-amber-500',
    tags: ['農曆春節', '紅金大吉', '年節禮盒', '賀歲迎新'],
    previewUrl: '/images/templates/lunarnewyear.jpg',
  },
  {
    id: 'midautumn',
    title: '中秋月圓團聚良辰',
    feeling: '皎潔明月秋水・暖橘燈火・闔家團圓溫潤感',
    category: 'holiday',
    applicability: '中秋月餅禮盒、烤肉聚餐、賞月茶飲酒品檔期',
    positivePrompt: 'Mid-Autumn festival reunion theme, luminous full moon, delicate paper lanterns, warm gentle autumn tones, cozy celebration atmosphere',
    negativePrompt: 'off-theme props, cluttered, low contrast, harsh harsh sunlight',
    paramAdvice: '4:5 或 3:4；滿月月色與暖燈光影層次',
    defaultAspect: '4:5',
    badge: '中秋專屬',
    gradient: 'from-indigo-900 via-blue-900 to-amber-400',
    tags: ['中秋月圓', '月餅禮盒', '闔家團圓', '秋季暖調'],
    previewUrl: '/images/templates/midautumn.jpg',
  },
  {
    id: 'christmas',
    title: '歡樂聖誕暖心雪季',
    feeling: '聖誕樹與白雪・紅綠金歡樂配色・交換禮物溫馨感',
    category: 'holiday',
    applicability: '年末聖誕大餐、交換禮物套組、冬季限定口味',
    positivePrompt: 'Christmas winter wonderland holiday, decorated pine tree, soft falling snow, classic red, green and warm gold accents, festive gift packaging aura',
    negativePrompt: 'off-theme summer props, cluttered, gloomy dark tones',
    paramAdvice: '4:5 或 1:1；聖誕紅綠金色澤搭配雪花光影',
    defaultAspect: '1:1',
    badge: '聖誕必推',
    gradient: 'from-emerald-700 via-red-700 to-amber-400',
    tags: ['聖誕歡樂', '雪花聖誕樹', '交換禮物', '冬季限定'],
    previewUrl: '/images/templates/christmas.jpg',
  },
  {
    id: 'newyear',
    title: '元旦跨年迎新希望',
    feeling: '璀璨跨年煙火・指針歸零・新年新願望正能量',
    category: 'holiday',
    applicability: '跨年夜狂歡、元旦開運好禮、新年立定目標特輯',
    positivePrompt: 'New Year celebration, midnight fireworks in sky, elegant clock countdown, optimistic resolution theme, sparkling gold and navy blue festival',
    negativePrompt: 'tiny text, cluttered, low contrast, daytime mundane scene',
    paramAdvice: '16:9 或 4:5；夜空煙火配以簡短新年願景標語',
    defaultAspect: '16:9',
    gradient: 'from-blue-900 via-indigo-900 to-purple-800',
    tags: ['跨年元旦', '迎新煙火', '開運祝福', '新年願景'],
    previewUrl: '/images/templates/newyear.jpg',
  },
  {
    id: 'valentine',
    title: '浪漫情人節甜密蜜',
    feeling: '浪漫愛心花瓣・雙人同享甜蜜・粉紅玫瑰柔美',
    category: 'holiday',
    applicability: '情人節雙人套餐、情侶對錶對杯、限定巧克力花束',
    positivePrompt: 'Valentine romantic theme, delicate heart petals, romantic couple or dual gift pairing, soft blush pink and deep rose palette, enchanting intimacy',
    negativePrompt: 'tiny text, cluttered, off-theme harsh lighting, corporate sterile look',
    paramAdvice: '4:5 或 1:1；粉桃玫瑰色調、浪漫溫馨',
    defaultAspect: '1:1',
    gradient: 'from-pink-500 via-rose-500 to-red-400',
    tags: ['浪漫情人節', '雙人套餐', '情侶對禮', '粉紅泡泡'],
    previewUrl: '/images/templates/valentine.jpg',
  },
  {
    id: 'mothersday',
    title: '溫馨母親節真摯感謝',
    feeling: '康乃馨溫柔花香・溫暖大地粉橘・無盡母愛感謝',
    category: 'holiday',
    applicability: '母親節孝親聚餐、保養呵護禮盒、全家福回憶專案',
    positivePrompt: 'Mother\'s Day celebration, gentle carnations, warm soothing peach and cream tones, heartfelt thank-you gratitude banner, tender family love',
    negativePrompt: 'harsh neon, loud jarring colors, cluttered, cold sterile backdrop',
    paramAdvice: '4:5 或 3:4；情感真摯、溫潤柔和暖光',
    defaultAspect: '4:5',
    gradient: 'from-rose-400 via-pink-300 to-amber-200',
    tags: ['溫馨母親節', '康乃馨', '呵護媽咪', '孝親聚餐'],
    previewUrl: '/images/templates/mothersday.jpg',
  },
  {
    id: 'fathersday',
    title: '感恩父親節沉穩獻禮',
    feeling: '深沉咖啡木質・硬派紳士品味・暖心默默付出',
    category: 'holiday',
    applicability: '父親節聚餐、手沖咖啡/威士忌/皮件禮物、老爸專屬',
    positivePrompt: 'Father\'s Day appreciation, rich warm leather and coffee wood tones, elegant gentleman aesthetic, heartfelt thank-you salute, refined masculinity',
    negativePrompt: 'tiny text, cluttered, childish props, overly frilly pastels',
    paramAdvice: '4:5 或 3:4；深藍、胡桃木或咖啡皮革色調',
    defaultAspect: '4:5',
    gradient: 'from-amber-900 via-stone-800 to-slate-900',
    tags: ['感恩父親節', '紳士品味', '老爸專屬', '沉穩暖男'],
    previewUrl: '/images/templates/fathersday.jpg',
  },
  {
    id: 'holiday',
    title: '全方位通用節日問候',
    feeling: '通用慶祝花環・明亮愉悅彩帶・溫暖節慶問候',
    category: 'holiday',
    applicability: '連續假期營業時間公告、品牌節日祝賀、連假專屬優惠',
    positivePrompt: 'holiday greeting card, festive celebratory elements, warm joyful wishes, signature brand colors, elegant festive decorative borders',
    negativePrompt: 'tiny text, cluttered, off-theme messy elements, dark gloom',
    paramAdvice: '4:5 或 1:1；圖文各半、節日元素合適簡約',
    defaultAspect: '1:1',
    gradient: 'from-teal-500 via-emerald-600 to-cyan-600',
    tags: ['連假公告', '節日祝福', '通用慶祝', '溫馨問候'],
    previewUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=800&q=80',
  },

  // ── 社群互動與教育篇（9 種）────────────────────────────────────────
  {
    id: 'pollquestion',
    title: '社群互動二選一投票卡',
    feeling: '二選一超大對照按鈕・挑起好奇心・強烈站隊感',
    category: 'social',
    applicability: '新口味票選、二選一世紀大對決、提升貼文互動留言率',
    positivePrompt: 'poll question interactive card, two distinct bold choices comparison, vote CTA button, vibrant contrasting brand colors, playful dilemma graphic',
    negativePrompt: 'tiny text, cluttered, too many options, low engagement look',
    paramAdvice: '4:5 或 9:16；左右或上下兩大選項極為分明',
    defaultAspect: '4:5',
    badge: '互動破表',
    gradient: 'from-violet-600 via-indigo-600 to-pink-500',
    tags: ['二選一', '社群投票', '留言互動', '激發站隊'],
    previewUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'quizcard',
    title: '趣味互動問答知識卡',
    feeling: '核心問題大字・選擇題選項卡・滑動下一張看解答',
    category: 'social',
    applicability: '品牌冷知識測驗、產品成分小考、IG 多圖輪播互動',
    positivePrompt: 'quiz card social graphic, prominent large question headline, multiple choice answer boxes, teaser for answer on next slide, clean educational layout',
    negativePrompt: 'tiny text, cluttered, confusing layout, multiple mixed questions',
    paramAdvice: '4:5 或 1:1；一題一卡、字體清晰好讀',
    defaultAspect: '4:5',
    gradient: 'from-blue-500 via-cyan-500 to-teal-500',
    tags: ['趣味問答', '知識小測驗', '輪播第二張', '增粉互動'],
    previewUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'checklist',
    title: '實用必備打勾清單',
    feeling: '復選打勾方塊・條列簡明・必存實用工具手冊',
    category: 'social',
    applicability: '野餐行前清單、採購必買攻略、品茶品酒五大步驟',
    positivePrompt: 'checklist infographic poster, crisp check box bullet points, concise items, elegant branded frame, highly bookmarkable resource card',
    negativePrompt: 'tiny text, cluttered, unending long text wall, disorganized',
    paramAdvice: '4:5 或 3:4；控制在 5~8 個條目內最耐讀',
    defaultAspect: '4:5',
    badge: '超高收藏',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-700',
    tags: ['必買清單', '行前準備', '打勾手冊', '收藏率高'],
    previewUrl: '/images/templates/checklist.jpg',
  },
  {
    id: 'dosdonts',
    title: '該做與不該做雙欄指引',
    feeling: '雙欄對照・綠色正確勾勾與紅色避坑叉叉・清晰直觀',
    category: 'social',
    applicability: '保養禁忌、吃法指南、新手避坑手冊、專業建議',
    positivePrompt: 'do and don\'t visual guide, two clear split columns, green checkmark and red cross icons, concise punchy tips, high clarity educational card',
    negativePrompt: 'tiny text, cluttered, long winding paragraphs, vague guidelines',
    paramAdvice: '4:5 或 3:4；每欄 3~4 條對照最乾淨',
    defaultAspect: '4:5',
    gradient: 'from-teal-600 via-emerald-600 to-rose-600',
    tags: ['該做與不該做', '避坑指南', '對照表', '專業教學'],
    previewUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'mythbust',
    title: '迷思破解真相揭秘',
    feeling: '謠言 VS 真相・強烈反轉感・打破常見誤解',
    category: 'social',
    applicability: '打破傳統迷思、原料闢謠、建立科學權威信任感',
    positivePrompt: 'myth versus fact breakdown card, two comparative sections, prominent "MYTH" and "FACT" badges, check and cross icons, truth revelation graphic',
    negativePrompt: 'tiny text, cluttered, defensive tone, endless text essays',
    paramAdvice: '4:5 或 3:4；「迷思」與「真相」對比鮮明',
    defaultAspect: '4:5',
    badge: '打破迷思',
    gradient: 'from-purple-600 via-rose-600 to-amber-500',
    tags: ['迷思破解', '事實真相', '打破誤解', '權威科普'],
    previewUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'quicktips',
    title: '三條快速秘訣圖卡',
    feeling: '三點乾貨精華・配對小圖標・短影音/貼文第一張',
    category: 'social',
    applicability: '日常小保養秘訣、快速沖泡技巧、美食搭配 3 招',
    positivePrompt: 'quick tips cheat-sheet, exactly 3 clear bullets, matching custom icons for each tip, bold catchy title, clean modern layout',
    negativePrompt: 'tiny text, cluttered, paragraphs too long, boring layout',
    paramAdvice: '4:5 或 9:16；剛好 3 條精煉短句最容易被記住',
    defaultAspect: '4:5',
    gradient: 'from-amber-500 via-orange-500 to-rose-500',
    tags: ['3大秘訣', '乾貨精華', '快速教學', '高轉發量'],
    previewUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hack',
    title: '生活妙用隱藏小技巧',
    feeling: '步驟拆解・意想不到的活用法・「原來還可以這樣」',
    category: 'social',
    applicability: '隱藏版喝法/吃法、舊瓶妙用回收改造、生活小妙招',
    positivePrompt: 'smart life hack card, subtle before-and-after hint, 1-2 easy actionable steps, bold intriguing title, smart clever idea showcase',
    negativePrompt: 'tiny text, cluttered, complicated instructions, blurry photos',
    paramAdvice: '4:5 或 1:1；一步驟配一圖最清晰',
    defaultAspect: '1:1',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-600',
    tags: ['隱藏喝法', '生活小技巧', '妙用拆解', '驚喜感'],
    previewUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'challenge',
    title: '打卡挑戰活動海報',
    feeling: '連續天數倒數・規則條列・完賽豐富獎勵誘惑',
    category: 'social',
    applicability: '7天健康打卡、21天喝好茶挑戰、社群打卡送好禮',
    positivePrompt: 'challenge campaign poster, day count tracker calendar, clear concise rule bullet points, irresistible prize showcase, energetic motivation tone',
    negativePrompt: 'tiny text, cluttered, complicated barrier to entry, dull colors',
    paramAdvice: '4:5 或 1:1；天數數字大、規則 3 條內清楚',
    defaultAspect: '4:5',
    gradient: 'from-orange-500 via-rose-500 to-purple-600',
    tags: ['打卡挑戰', '天數追蹤', '完賽好禮', '社群參與'],
    previewUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'countdownstory',
    title: '限動倒數迫近焦點',
    feeling: '超大倒數倒數數字・全螢幕緊湊感・立即滑動參與',
    category: 'social',
    applicability: 'IG Stories 限動發布、最後幾小時開搶、活動即將開始',
    positivePrompt: 'countdown story layout, gigantic focal number, precise date and time, clear swipe-up or click CTA, modern clean mobile frame',
    negativePrompt: 'tiny text, cluttered, low contrast, horizontal orientation',
    paramAdvice: '9:16 手機全螢幕比例；數字超大置中',
    defaultAspect: '9:16',
    gradient: 'from-rose-600 via-red-600 to-orange-500',
    tags: ['限動倒數', '9:16全屏', '最後幾小時', '緊湊大字'],
    previewUrl: 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=800&q=80',
  },

  // ── 信任與證言篇（8 種）────────────────────────────────────────
  {
    id: 'reviewhighlight',
    title: '買家好評金句摘錄',
    feeling: '閃耀五星評分・一句話顧客口碑金句・真實度滿分',
    category: 'trust',
    applicability: '好評見證、廣告投放信任素材、解決疑慮下單最後推手',
    positivePrompt: 'customer review highlight card, 5 golden star ratings, short impactful real quote, verified buyer badge, pristine product photography',
    negativePrompt: 'tiny text, cluttered, unreadably long review paragraphs, fake look',
    paramAdvice: '4:5 或 1:1；一句話金句加粗置中',
    defaultAspect: '1:1',
    badge: '轉化催化劑',
    gradient: 'from-amber-400 via-yellow-500 to-orange-400',
    tags: ['五星好評', '真實口碑', '顧客見證', '信任背書'],
    previewUrl: '/images/templates/reviewhighlight.jpg',
  },
  {
    id: 'ratingstars',
    title: '綜合星級超高評分',
    feeling: '特大評分數字 (如 4.9 分)・滿意人數・高品質產品特寫',
    category: 'trust',
    applicability: '官網信任區塊、熱銷榜單商品卡、外送平台高分推薦',
    positivePrompt: 'rating stars showcase banner, large 4.9/5 score typography, thousands of reviews count, clean product hero shot, credible social proof',
    negativePrompt: 'tiny text, cluttered, unbelievable fake layout, noisy background',
    paramAdvice: '1:1 或 4:5；4.9/5.0 數字特大鮮明',
    defaultAspect: '1:1',
    gradient: 'from-yellow-500 via-amber-500 to-orange-600',
    tags: ['4.9高分', '千人狂推', '綜合評分', '口碑推薦'],
    previewUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'proofpoint',
    title: '硬核數據指標背書',
    feeling: '特大客觀數據・極簡佐證圖解・無可辯駁的說服力',
    category: 'trust',
    applicability: '「98% 回購率」、「累計狂銷 10 萬杯」、「通過 400 項檢驗」',
    positivePrompt: 'proof point data card, huge authoritative metric number, short crystal-clear caption, minimalist verified chart, bulletproof credibility layout',
    negativePrompt: 'tiny text, cluttered, overly complex spreadsheets, doubtful data',
    paramAdvice: '1:1 或 4:5；數字最大、字數最少最有力',
    defaultAspect: '1:1',
    badge: '數據說話',
    gradient: 'from-blue-600 via-indigo-600 to-cyan-600',
    tags: ['客觀數據', '回購率98%', '權威檢驗', '銷量紀錄'],
    previewUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'casestudy',
    title: '真實案例研究見證',
    feeling: '關鍵成效指標・前後故事縮影・真實轉變力量',
    category: 'trust',
    applicability: 'B2B 合作成果、加盟主成功故事、學員蛻變實證',
    positivePrompt: 'case study success story card, remarkable before-and-after outcome metric, inspiring summary narrative, professional brand framing',
    negativePrompt: 'tiny text, cluttered, endless corporate jargon, vague outcomes',
    paramAdvice: '4:5 或 16:9；挑出最亮眼的 1~2 個成長倍數指標',
    defaultAspect: '4:5',
    gradient: 'from-slate-700 via-indigo-800 to-zinc-900',
    tags: ['成功案例', '加盟見證', 'B2B成果', '真實轉變'],
    previewUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'presslogo',
    title: '權威主流媒體露出',
    feeling: '各大知名媒體 Logo 陣列・黑白一致・權威公信力',
    category: 'trust',
    applicability: '官網信任區塊、募資專案媒體報導陣容、融資發布',
    positivePrompt: 'press logos media feature grid, elegant monochrome or subtle gray brand logos, clean spacious layout, as seen on authoritative badge',
    negativePrompt: 'color clashing logos, uneven chaotic sizing, cluttered background',
    paramAdvice: '16:9 或 3:4；媒體商標統一黑白或單色排列',
    defaultAspect: '16:9',
    gradient: 'from-gray-700 via-slate-800 to-zinc-800',
    tags: ['媒體報導', '新聞採訪', '各大報推薦', '權威公信'],
    previewUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'awardbadge',
    title: '年度大獎榮譽徽章',
    feeling: '燙金得獎緞帶・獲獎年份標註・品質最高殊榮',
    category: 'trust',
    applicability: '食品米其林 iTQi 獲獎、年度設計大獎、品質金獎標章',
    positivePrompt: 'prestige award badge, gold ribbon with laurel wreath, award year, official category recognition, refined celebratory trophy tone',
    negativePrompt: 'tiny text, cluttered, cheap clip-art look, gaudy textures',
    paramAdvice: '1:1 方形；金牌緞帶與文字洗煉大方',
    defaultAspect: '1:1',
    badge: '品質金獎',
    gradient: 'from-yellow-500 via-amber-600 to-yellow-700',
    tags: ['榮譽得獎', '金牌認證', 'iTQi殊榮', '品質背書'],
    previewUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'certification',
    title: '國際權威認證標章',
    feeling: '有機/清真/SGS/環保等清晰標章・純淨放心品質',
    category: 'trust',
    applicability: 'SGS 檢驗合格、清真認證、有機純天然標示、無添加保證',
    positivePrompt: 'official certification marks showcase, clean recognizable safety icons, concise safety labels, crisp trustworthy brand card',
    negativePrompt: 'tiny text, cluttered, illegible seals, low contrast',
    paramAdvice: '4:5 或 3:4；標章排版工整有秩序',
    defaultAspect: '4:5',
    gradient: 'from-emerald-600 via-teal-700 to-slate-800',
    tags: ['SGS檢驗', '國際認證', '安全無添加', '食安守護'],
    previewUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'sustainability',
    title: '綠色永續環保承諾',
    feeling: '綠葉環保圖標・減碳數據・大自然永續純淨感',
    category: 'trust',
    applicability: '環保減塑杯、100% 可回收包裝、在地友善小農採購',
    positivePrompt: 'environmental sustainability commitment, green leaf and recycle symbol, tangible eco metric, clean natural organic aesthetics, ESG friendly',
    negativePrompt: 'tiny text, cluttered, greenwashing fake look, industrial smog',
    paramAdvice: '4:5 或 16:9；一句話明確點出減碳或減塑具體成果',
    defaultAspect: '4:5',
    gradient: 'from-emerald-500 via-teal-600 to-green-700',
    tags: ['綠色環保', '永續減碳', '友善在地', 'ESG承諾'],
    previewUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
  },

  // ── 商業公告與運營篇（11 種）────────────────────────────────────────
  {
    id: 'comingsoon',
    title: '神秘新品即將上市',
    feeling: '局部遮擋剪裁・倒數上市日期・滿滿期待感與好奇心',
    category: 'business',
    applicability: '季末新品預告、重量級跨界聯名預熱、旗艦機型登場前夕',
    positivePrompt: 'coming soon teaser, intriguing partial crop of product, bold "Coming Soon" typography with launch date, subtle silhouette, anticipation mood',
    negativePrompt: 'tiny text, cluttered, completely visible product, spoiling all surprises',
    paramAdvice: '4:5 或 16:9；適度剪裁遮擋、保留懸念',
    defaultAspect: '4:5',
    badge: '神秘引流',
    gradient: 'from-indigo-950 via-purple-900 to-slate-900',
    tags: ['即將上市', '新品預告', '神秘微透', '期待感爆棚'],
    previewUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'reveal',
    title: '新品震撼全貌揭曉',
    feeling: '商品完整重磅亮相・核心賣點一句話擊中・立即選購',
    category: 'business',
    applicability: '發表會後正式公開、預告揭曉、現貨全面開賣',
    positivePrompt: 'grand reveal visual, pristine full product hero reveal, striking key benefit headline, compelling direct CTA, dynamic celebratory launch lighting',
    negativePrompt: 'tiny text, cluttered, dull everyday lighting, obscured details',
    paramAdvice: '16:9 或 4:5；產品細節一覽無遺、光線霸氣',
    defaultAspect: '16:9',
    badge: '正式登場',
    gradient: 'from-fuchsia-600 via-violet-600 to-indigo-700',
    tags: ['重磅揭曉', '正式開賣', '核心賣點', '現貨到門市'],
    previewUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'announcement',
    title: '重要服務正式公告',
    feeling: '重要圖標・條列式簡明重點・官方權威可靠度',
    category: 'business',
    applicability: '營業時間調整、國定假日專案服務、重大通知發布',
    positivePrompt: 'official service announcement, clear loudspeaker megaphone icon, concise structured bulletin points, clean professional corporate layout',
    negativePrompt: 'tiny text, cluttered, emotional chaotic tone, illegible font',
    paramAdvice: '4:5 或 3:4；條列重點、不囉唆',
    defaultAspect: '4:5',
    gradient: 'from-blue-600 via-slate-700 to-indigo-800',
    tags: ['官方公告', '重要通知', '營業異動', '清楚條列'],
    previewUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'relocation',
    title: '門市喬遷新址啟事',
    feeling: '新舊地址對照・精巧地圖指引・新店升級期待',
    category: 'business',
    applicability: '門市搬遷新址、辦公室升級喬遷、新店擴大營業指南',
    positivePrompt: 'store relocation announcement, elegant map pointer pin, side-by-side old and new address comparison, celebratory grand reopening teaser',
    negativePrompt: 'tiny text, cluttered, messy illegible map, chaotic arrows',
    paramAdvice: '4:5 或 3:4；新地址字體特大、地標明顯',
    defaultAspect: '4:5',
    gradient: 'from-teal-500 via-emerald-600 to-cyan-600',
    tags: ['喬遷新喜', '門市搬遷', '新地址指引', '擴大營業'],
    previewUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'tempclose',
    title: '門市內部整修暫停公告',
    feeling: '貼心致歉・裝修原因與重開日期・替代購買通路指引',
    category: 'business',
    applicability: '門市內部改裝、設備定期保養、連假店休通知',
    positivePrompt: 'temporary closure polite notice, renovation explanation, clear reopening date, friendly alternative channel and online ordering prompt',
    negativePrompt: 'tiny text, cluttered, alarming negative tone, confusing dates',
    paramAdvice: '4:5 或 1:1；重新營業日期清晰放中間',
    defaultAspect: '1:1',
    gradient: 'from-amber-600 via-stone-700 to-slate-800',
    tags: ['內部改裝', '設備保養', '暫停營業', '重開日期'],
    previewUrl: 'https://images.unsplash.com/photo-1519750157634-b6d493a0f77c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hiring',
    title: '菁英招募職缺海報',
    feeling: '醒目大職稱・核心福利誘人・「立即投遞簡歷」',
    category: 'business',
    applicability: '門市正職/兼職招募、店長副店長、辦公室行銷夥伴徵才',
    positivePrompt: 'we are hiring recruitment poster, bold prominent role title, compelling benefits highlights, inviting apply now CTA, modern attractive workplace vibe',
    negativePrompt: 'tiny text, cluttered, boring standard job board look, vague roles',
    paramAdvice: '4:5 或 1:1；職缺職稱必須是最大視覺亮點',
    defaultAspect: '4:5',
    badge: '廣納人才',
    gradient: 'from-indigo-600 via-blue-600 to-teal-500',
    tags: ['我們在找你', '人才徵招', '門市正職', '福利優渥'],
    previewUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'franchise',
    title: '加盟連鎖招商盛會',
    feeling: '總部堅強後盾・開店投資區間・說明會預約號召',
    category: 'business',
    applicability: '連鎖加盟招募、海外拓點授權、加盟說明會場次公布',
    positivePrompt: 'franchise opportunity recruitment poster, turnkey business support highlights, investment range hint, confident expansion tone',
    negativePrompt: 'tiny text, cluttered, wild unrealistic promises, confusing terms',
    paramAdvice: '4:5 或 3:4；強調總部後援系統與成功模型',
    defaultAspect: '4:5',
    badge: '連鎖拓點',
    gradient: 'from-amber-600 via-orange-600 to-red-600',
    tags: ['連鎖加盟', '開店輔導', '總部支援', '說明會報名'],
    previewUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'partnership',
    title: '雙品牌強強聯名合作',
    feeling: '雙方 Logo 平分秋色・1+1大於2・強烈聯名火花',
    category: 'business',
    applicability: '跨界品牌聯名商品、雙方通路聯合曝光、聯名快閃',
    positivePrompt: 'joint brand partnership announcement, balanced display of dual logos, collaborative synergy benefit statement, exciting limited edition collab',
    negativePrompt: 'tiny text, cluttered, one logo overpowering another, mismatched vibes',
    paramAdvice: '16:9 或 4:5；雙方品牌 Logo 尺寸平衡尊重',
    defaultAspect: '16:9',
    badge: '跨界聯名',
    gradient: 'from-purple-600 via-pink-600 to-indigo-600',
    tags: ['跨界聯名', '強強聯手', '1+1大於2', '限量合作款'],
    previewUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'appupdate',
    title: '全新版本 APP 上線',
    feeling: '全新升級版本號・核心新功能三大亮點・即刻更新',
    category: 'business',
    applicability: 'APP/系統改版發布、點數系統升級、全新功能通知',
    positivePrompt: 'app update release banner, bold version number, sleek mobile app screen preview, 3 key new feature bullet highlights, update now button CTA',
    negativePrompt: 'tiny text, cluttered, complicated changelog list, unreadable UI',
    paramAdvice: '4:5 或 1:1；挑選最吸引人的 3 個新功能即可',
    defaultAspect: '4:5',
    gradient: 'from-cyan-500 via-blue-600 to-violet-600',
    tags: ['全新改版', 'APP更新', '功能升級', '即刻體驗'],
    previewUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'systemmaint',
    title: '系統定期維護升級',
    feeling: '維護時段清晰・影響範圍清楚・貼心抱歉與期待',
    category: 'business',
    applicability: '伺服器升級維護、資料庫深夜重整、線上結帳短暫維修',
    positivePrompt: 'scheduled system maintenance notice, polite wrench and server icon, clear exact time window, polite apology and customer support assurance',
    negativePrompt: 'tiny text, cluttered, technical programmer jargon, alarming error style',
    paramAdvice: '16:9 或 4:5；維護起訖時段一清二楚',
    defaultAspect: '16:9',
    gradient: 'from-slate-600 via-zinc-700 to-stone-800',
    tags: ['系統維護', '深夜升級', '時段公告', '貼心致歉'],
    previewUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'beta',
    title: '限量搶先內測體驗',
    feeling: '限量內測名額・尊榮特邀感・共同打造完美產品',
    category: 'business',
    applicability: '新產品封測品嚐、私密體驗官招募、新服務內測',
    positivePrompt: 'beta testing program invitation, exclusive insider access badge, simple qualification steps, deadline to register, futuristic confidential excitement',
    negativePrompt: 'tiny text, cluttered, vague requirements, boring survey look',
    paramAdvice: '4:5 或 3:4；內測名額有限、專屬特邀感強',
    defaultAspect: '4:5',
    gradient: 'from-violet-700 via-indigo-700 to-cyan-600',
    tags: ['限量內測', '體驗官招募', '搶先品嚐', '共同創造'],
    previewUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
  },
]
