/**
 * Seed Knowledge Base for Vietnam Legal & Business Compliance AI System
 *
 * 預載越南核心官方商事、投資、食品安全與特別消費稅法規，
 * 建立 Điều (條) / Khoản (款) / Điểm (點) 之精確對應。
 */

import { LegalDocument, LegalNode, ProcedureCatalog, ProcedureStep, ProcedureDossierItem, CrossBorderComplianceRule } from './types'

export const SEED_LEGAL_DOCUMENTS: LegalDocument[] = [
  {
    id: 'doc-law-55-2010',
    country_code: 'VN',
    document_number: '55/2010/QH12',
    document_type: 'Luật',
    title_vi: 'Luật An toàn thực phẩm',
    title_en: 'Law on Food Safety',
    title_zh: '越南食品安全法',
    issuing_authority: 'Quốc hội',
    signer: 'Nguyễn Phú Trọng',
    issue_date: '2010-06-17',
    effective_date: '2011-07-01',
    expiry_date: null,
    status: 'ACTIVE',
    is_consolidated: false,
    source_tier: 1,
    source_url: 'https://vbpl.vn/TW/Pages/vbpq-toanvan.aspx?ItemID=25841',
    metadata: { industry: 'food_beverage', category: 'food_safety' },
  },
  {
    id: 'doc-decree-15-2018',
    country_code: 'VN',
    document_number: '15/2018/NĐ-CP',
    document_type: 'Nghị định',
    title_vi: 'Nghị định quy định chi tiết thi hành một số điều của Luật an toàn thực phẩm',
    title_en: 'Decree detailing the implementation of a number of articles of the Law on Food Safety',
    title_zh: '落實食品安全法若干條款施行細則之第 15/2018/NĐ-CP 號法令',
    issuing_authority: 'Chính phủ',
    signer: 'Nguyễn Xuân Phúc',
    issue_date: '2018-02-02',
    effective_date: '2018-02-02',
    expiry_date: null,
    status: 'ACTIVE',
    is_consolidated: false,
    source_tier: 1,
    source_url: 'https://vanban.chinhphu.vn/?pageid=27160&docid=192801',
    metadata: { industry: 'food_beverage', category: 'food_safety', implements: '55/2010/QH12' },
  },
  {
    id: 'doc-law-61-2020',
    country_code: 'VN',
    document_number: '61/2020/QH14',
    document_type: 'Luật',
    title_vi: 'Luật Đầu tư',
    title_en: 'Law on Investment',
    title_zh: '越南投資法',
    issuing_authority: 'Quốc hội',
    signer: 'Nguyễn Thị Kim Ngân',
    issue_date: '2020-06-17',
    effective_date: '2021-01-01',
    expiry_date: null,
    status: 'ACTIVE',
    is_consolidated: false,
    source_tier: 1,
    source_url: 'https://vbpl.vn/TW/Pages/vbpq-toanvan.aspx?ItemID=143213',
    metadata: { industry: 'general', category: 'investment' },
  },
  {
    id: 'doc-law-59-2020',
    country_code: 'VN',
    document_number: '59/2020/QH14',
    document_type: 'Luật',
    title_vi: 'Luật Doanh nghiệp',
    title_en: 'Law on Enterprises',
    title_zh: '越南企業法',
    issuing_authority: 'Quốc hội',
    signer: 'Nguyễn Thị Kim Ngân',
    issue_date: '2020-06-17',
    effective_date: '2021-01-01',
    expiry_date: null,
    status: 'ACTIVE',
    is_consolidated: false,
    source_tier: 1,
    source_url: 'https://vbpl.vn/TW/Pages/vbpq-toanvan.aspx?ItemID=143214',
    metadata: { industry: 'general', category: 'enterprise' },
  },
  {
    id: 'doc-draft-sugar-tax-2025',
    country_code: 'VN',
    document_number: 'Dự thảo Luật Thuế TTĐB (sửa đổi)',
    document_type: 'Luật',
    title_vi: 'Dự thảo Luật Thuế Tiêu thụ Đặc biệt (sửa đổi)',
    title_en: 'Draft Law on Special Consumption Tax (Amended)',
    title_zh: '越南特別消費稅法修正案（草案）',
    issuing_authority: 'Bộ Tài chính / Quốc hội',
    signer: 'Bộ Tài chính chủ trì soạn thảo',
    issue_date: '2024-11-01',
    effective_date: '2026-01-01',
    expiry_date: null,
    status: 'NOT_YET_EFFECTIVE',
    is_consolidated: false,
    source_tier: 2,
    source_url: 'https://mof.gov.vn/webcenter/portal/btc/r/m/tin-tuc-su-kien/chi-tiet-tin?dDocName=MOFUCM314059',
    metadata: { industry: 'food_beverage', category: 'tax', sugar_tax: true },
  },
]

export const SEED_LEGAL_NODES: LegalNode[] = [
  // 15/2018/NĐ-CP Điều 4 (Tự công bố sản phẩm)
  {
    id: 'node-nd15-art4-cl1',
    document_id: 'doc-decree-15-2018',
    country_code: 'VN',
    node_type: 'CLAUSE',
    article_number: 'Điều 4',
    article_title: 'Tự công bố sản phẩm',
    clause_number: 'Khoản 1',
    node_locator: 'Điều 4, Khoản 1',
    original_text_vi: 'Tổ chức, cá nhân sản xuất, kinh doanh thực phẩm thực hiện tự công bố thực phẩm đã qua chế biến bao gói sẵn, phụ gia thực phẩm, chất hỗ trợ chế biến thực phẩm, dụng cụ chứa đựng thực phẩm, vật liệu bao gói tiếp xúc trực tiếp với thực phẩm trừ các sản phẩm quy định tại khoản 2 Điều này và Điều 6 Nghị định này.',
    translated_text_zh: '生產、經營食品之組織及個人，除本條第 2 款及本法令第 6 條所規定之產品外，應對預包裝加工食品、食品添加物、食品加工助劑、食品盛裝容器及直接接觸食品之包裝材料進行【產品自主公告 (Tự công bố)】。',
    effective_from: '2018-02-02',
    status: 'ACTIVE',
  },
  // 15/2018/NĐ-CP Điều 11 (Cơ sở không thuộc diện cấp Giấy chứng nhận ATTP)
  {
    id: 'node-nd15-art11-cl1-ptg',
    document_id: 'doc-decree-15-2018',
    country_code: 'VN',
    node_type: 'POINT',
    article_number: 'Điều 11',
    article_title: 'Cơ sở không thuộc diện cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm',
    clause_number: 'Khoản 1',
    point_number: 'Điểm g',
    node_locator: 'Điều 11, Khoản 1, Điểm g',
    original_text_vi: 'Nhà hàng trong khách sạn; Bếp ăn tập thể không có đăng ký ngành nghề kinh doanh thực phẩm; Kinh doanh thức ăn đường phố.',
    translated_text_zh: '飯店內餐廳；未登記食品營業項目之集體廚房；以及路邊攤販，免除申請食品安全合格機構證書。一般門市若有固定經營場所且商業登記包含食品餐飲者，仍應依法取得證書。',
    effective_from: '2018-02-02',
    status: 'ACTIVE',
  },
  // 15/2018/NĐ-CP Điều 12 (Cấp Giấy chứng nhận ATTP)
  {
    id: 'node-nd15-art12-cl1',
    document_id: 'doc-decree-15-2018',
    country_code: 'VN',
    node_type: 'CLAUSE',
    article_number: 'Điều 12',
    article_title: 'Hồ sơ, trình tự, thủ tục cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm',
    clause_number: 'Khoản 1',
    node_locator: 'Điều 12, Khoản 1',
    original_text_vi: 'Hồ sơ xin cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm gồm: Đơn đề nghị theo Mẫu số 01; Bản sao Giấy chứng nhận đăng ký kinh doanh; Bản thuyết minh về cơ sở vật chất, trang thiết bị; Giấy xác nhận đủ sức khỏe của chủ cơ sở và người trực tiếp sản xuất; Giấy xác nhận đã được tập huấn kiến thức về an toàn thực phẩm.',
    translated_text_zh: '申請食品安全合格機構證書應備文件包括：依表格 Mẫu số 01 提出之申請書；營業登記證副本；經營場所設施與設備說明書；負責人及直接從事調製人員之合格健康檢查證明；食品安全衛生知識培訓合格證明。',
    effective_from: '2018-02-02',
    status: 'ACTIVE',
  },
  // 61/2020/QH14 Điều 37 (Cấp Giấy chứng nhận đăng ký đầu tư IRC)
  {
    id: 'node-dt61-art37-cl1',
    document_id: 'doc-law-61-2020',
    country_code: 'VN',
    node_type: 'CLAUSE',
    article_number: 'Điều 37',
    article_title: 'Trường hợp thực hiện thủ tục cấp Giấy chứng nhận đăng ký đầu tư',
    clause_number: 'Khoản 1',
    node_locator: 'Điều 37, Khoản 1',
    original_text_vi: 'Các trường hợp phải thực hiện thủ tục cấp Giấy chứng nhận đăng ký đầu tư: Dự án đầu tư của nhà đầu tư nước ngoài; Dự án đầu tư của tổ chức kinh tế quy định tại khoản 1 Điều 23 của Luật này.',
    translated_text_zh: '必須辦理投資登記證書 (IRC) 核發手續之情形：外國投資人之投資項目；或由外資持股達 50% 以上經濟組織所實施之投資項目。即外商在越南新設公司或開店前，必須先取得投資登記證書 (IRC)。',
    effective_from: '2021-01-01',
    status: 'ACTIVE',
  },
  // 59/2020/QH14 Điều 27 (Cấp Giấy chứng nhận đăng ký doanh nghiệp ERC)
  {
    id: 'node-dn59-art27-cl1',
    document_id: 'doc-law-59-2020',
    country_code: 'VN',
    node_type: 'CLAUSE',
    article_number: 'Điều 27',
    article_title: 'Cấp Giấy chứng nhận đăng ký doanh nghiệp',
    clause_number: 'Khoản 1',
    node_locator: 'Điều 27, Khoản 1',
    original_text_vi: 'Doanh nghiệp được cấp Giấy chứng nhận đăng ký doanh nghiệp khi có đủ các điều kiện: Ngành, nghề đăng ký kinh doanh không bị cấm; Có hồ sơ hợp lệ; Nộp đủ lệ phí đăng ký doanh nghiệp theo quy định.',
    translated_text_zh: '企業具備下列條件者，主管機關應於 3 個工作日內核發企業登記證 (ERC)：申請之營業項目非屬法律禁止之行業；備齊法定合格文件；依規定繳納營業登記規費。外資企業於取得 IRC 後，始得辦理 ERC。',
    effective_from: '2021-01-01',
    status: 'ACTIVE',
  },
  // Dự thảo Luật Thuế TTĐB (含糖飲料特別消費稅)
  {
    id: 'node-sugartax-art2-cl1-pth',
    document_id: 'doc-draft-sugar-tax-2025',
    country_code: 'VN',
    node_type: 'POINT',
    article_number: 'Điều 2',
    article_title: 'Đối tượng chịu thuế',
    clause_number: 'Khoản 1',
    point_number: 'Điểm h',
    node_locator: 'Điều 2, Khoản 1, Điểm h',
    original_text_vi: 'Nước giải khát theo Tiêu chuẩn Việt Nam (TCVN) có hàm lượng đường trên 5g/100ml áp dụng mức thuế suất thuế tiêu thụ đặc biệt là 10%.',
    translated_text_zh: '依據越南國家標準 (TCVN)，含糖量超過 5g/100ml 之軟性飲料（含調製手搖飲品與包裝飲料），適用 10% 之特別消費稅稅率。天然乳製品與無額外添加糖之 100% 果汁除外。',
    effective_from: '2026-01-01',
    status: 'NOT_YET_EFFECTIVE',
  },
]

export const SEED_PROCEDURES: ProcedureCatalog[] = [
  {
    id: 'proc-food-safety-cert',
    country_code: 'VN',
    code: 'B-BTT-001-ATTP',
    name_vi: 'Cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm',
    name_zh: '申請食品安全合格機構證書 (ATTP)',
    name_en: 'Certificate of Food Safety Eligibility',
    category: 'food_safety',
    industry: 'beverage_restaurant',
    province: 'ALL',
    competent_authority: 'Chi cục An toàn vệ sinh thực phẩm (Sở Y tế) hoặc Ban Quản lý ATTP',
    governing_body: 'Bộ Y tế',
    submission_method: 'BOTH',
    online_url: 'https://dichvucong.gov.vn',
    processing_time_days: 15,
    official_fee_vnd: 700000,
    fee_notes: '評定檢驗規費：700,000 VND / 每次現場審查',
    result_document: 'Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm',
    conditions: '具備符合標準之作業場所、不生鏽器具設備、水源檢驗合格報告、員工健康體檢證明與食安培訓合格證書。',
    source_url: 'https://dichvucong.gov.vn',
  },
  {
    id: 'proc-irc-license',
    country_code: 'VN',
    code: 'B-BKH-002-IRC',
    name_vi: 'Cấp Giấy chứng nhận đăng ký đầu tư (IRC) cho nhà đầu tư nước ngoài',
    name_zh: '外商申請投資登記證 (IRC)',
    name_en: 'Investment Registration Certificate for Foreign Investors',
    category: 'investment',
    industry: 'general',
    province: 'ALL',
    competent_authority: 'Sở Kế hoạch và Đầu tư tỉnh/thành phố (Sở KH&ĐT)',
    governing_body: 'Bộ Kế hoạch và Đầu tư',
    submission_method: 'BOTH',
    online_url: 'https://fdi.gov.vn',
    processing_time_days: 15,
    official_fee_vnd: 0,
    fee_notes: '官方規費為免收，但需自行負擔文件外交使館認證與公證翻譯費用。',
    result_document: 'Giấy chứng nhận đăng ký đầu tư (IRC)',
    conditions: '外國投資人資金來源合法證明（銀行存款餘額或母公司財報審計）、租賃合約備查、符合外資准入負面清單。',
    source_url: 'https://dichvucong.gov.vn',
  },
  {
    id: 'proc-erc-license',
    country_code: 'VN',
    code: 'B-BKH-003-ERC',
    name_vi: 'Cấp Giấy chứng nhận đăng ký doanh nghiệp (ERC)',
    name_zh: '企業營業執照/公司設立登記 (ERC)',
    name_en: 'Enterprise Registration Certificate',
    category: 'enterprise',
    industry: 'general',
    province: 'ALL',
    competent_authority: 'Phòng Đăng ký kinh doanh - Sở Kế hoạch và Đầu tư',
    governing_body: 'Bộ Kế hoạch và Đầu tư',
    submission_method: 'ONLINE',
    online_url: 'https://dangkykinhdoanh.gov.vn',
    processing_time_days: 3,
    official_fee_vnd: 50000,
    fee_notes: '線上申辦官方公告規費 50,000 VND，全國公開企業資訊登報費 100,000 VND。',
    result_document: 'Giấy chứng nhận đăng ký doanh nghiệp (ERC)',
    conditions: '需先取得 IRC 投資許可證（若為外資），並具備合法公司章程與法定代表人指派書。',
    source_url: 'https://dangkykinhdoanh.gov.vn',
  },
]

export const SEED_CROSS_BORDER_RULES: CrossBorderComplianceRule[] = [
  {
    id: 'rule-pearls-import',
    origin_country: 'TW',
    destination_country: 'VN',
    category: 'FOOD',
    item_name_zh: '珍珠粉圓 / 樹薯澱粉製品 (Tapioca Pearls)',
    hs_code: '1903.00.00',
    regulatory_requirements: '1. 進口前需在越南辦理食品安全自宣告 (Tự công bố sản phẩm)；2. 需檢附台灣官方出口衛生證明與原產地證明 (Certificate of Origin - Form E 或一般 CO)；3. 抵港後需接受國家食品安全邊境抽驗。',
    tariff_rate_percentage: 15.0,
    vat_rate_percentage: 8.0,
    special_consumption_tax: 0.0,
    required_certificates: ['Certificate of Analysis (COA)', 'Certificate of Free Sale (CFS)', 'Certificate of Origin (CO)', 'Health Certificate'],
    official_source_url: 'https://customs.gov.vn',
  },
  {
    id: 'rule-tea-import',
    origin_country: 'TW',
    destination_country: 'VN',
    category: 'FOOD',
    item_name_zh: '台灣烏龍茶葉 / 高山茶 (Tea Leaves)',
    hs_code: '0902.20.90',
    regulatory_requirements: '1. 越南對未包裝茶葉課徵農產品保護關稅 (關稅達 30-40%)；2. 抵達越南港口前必須通過植物檢疫 (Kiểm dịch thực vật)；3. 每批次需附帶農藥殘留檢驗報告，農殘需符合越南衛生部 Thông tư 50/2016/TT-BYT 規定。',
    tariff_rate_percentage: 35.0,
    vat_rate_percentage: 5.0,
    special_consumption_tax: 0.0,
    required_certificates: ['Phytosanitary Certificate (植物檢疫證)', 'COA', 'Certificate of Origin'],
    official_source_url: 'https://customs.gov.vn',
  },
  {
    id: 'rule-sealing-machine',
    origin_country: 'TW',
    destination_country: 'VN',
    category: 'EQUIPMENT',
    item_name_zh: '飲料封口機 / 果糖定量機 / 萃茶機 (Beverage Sealing Machine)',
    hs_code: '8422.30.00',
    regulatory_requirements: '1. 全新設備適用正常進口手續，二手中古設備需符合越南總理第 18/2019/QĐ-TTg 號決定（機齡不超過 10 年且需具有認證機構檢驗報告）；2. 電器安全需符合越南國家標準 TCVN，電壓規格為 220V/50Hz。',
    tariff_rate_percentage: 0.0, // WTO / 優惠稅率多數為 0%
    vat_rate_percentage: 8.0,
    special_consumption_tax: 0.0,
    required_certificates: ['Commercial Invoice', 'Packing List', 'Bill of Lading', 'CQ (品質證明)'],
    official_source_url: 'https://customs.gov.vn',
  },
]
