-- Migration: 20260913_social_matrix.sql
-- Description: Schema for Marketing Social Media Matrix & Auto Warm-up System (Proxy Pool, Accounts, Campaigns, Logs)

-- 1. Proxies table (家用原生靜態住宅 IP + 商業住宅代理池)
CREATE TABLE IF NOT EXISTS public.marketing_proxies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  proxy_type TEXT NOT NULL DEFAULT 'home_static', -- 'home_static' | 'residential' | 'mobile_4g'
  protocol TEXT NOT NULL DEFAULT 'http',         -- 'http' | 'https' | 'socks5'
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  username TEXT,
  password TEXT,
  country TEXT DEFAULT 'TW',
  city TEXT,
  isp TEXT,                                      -- e.g. "聯禾有線電視", "中華電信", "IPRoyal"
  status TEXT DEFAULT 'active',                  -- 'active' | 'testing' | 'error' | 'offline'
  latency_ms INTEGER DEFAULT 0,
  last_checked_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index on user_id
CREATE INDEX IF NOT EXISTS idx_marketing_proxies_user ON public.marketing_proxies(user_id);

-- Enable RLS
ALTER TABLE public.marketing_proxies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own proxies"
  ON public.marketing_proxies
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 2. Social Accounts Matrix (社群矩陣與自動養號帳號)
CREATE TABLE IF NOT EXISTS public.marketing_social_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,                        -- 'facebook' | 'instagram' | 'threads' | 'tiktok' | 'dcard' | 'x'
  account_name TEXT NOT NULL,
  account_handle TEXT,
  avatar_url TEXT,
  proxy_id UUID REFERENCES public.marketing_proxies(id) ON DELETE SET NULL,
  warmup_day INTEGER NOT NULL DEFAULT 1,         -- Day 1 to Day 14+
  status TEXT NOT NULL DEFAULT 'warming',        -- 'warming' | 'mature' | 'cooling' | 'banned' | 'idle'
  health_score INTEGER NOT NULL DEFAULT 60,      -- 0 - 100
  daily_actions_count INTEGER NOT NULL DEFAULT 0,
  max_daily_actions INTEGER NOT NULL DEFAULT 5,
  target_niches TEXT[] DEFAULT '{}',
  last_action_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index on user_id and proxy_id
CREATE INDEX IF NOT EXISTS idx_marketing_social_accounts_user ON public.marketing_social_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_social_accounts_proxy ON public.marketing_social_accounts(proxy_id);

-- Enable RLS
ALTER TABLE public.marketing_social_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own social accounts"
  ON public.marketing_social_accounts
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 3. Social Matrix Campaigns & Dispatches (社群廣告矩陣與發行活動)
CREATE TABLE IF NOT EXISTS public.marketing_social_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  industry TEXT NOT NULL,
  core_product TEXT NOT NULL,
  target_audience TEXT,
  offer TEXT,
  cta_link TEXT,
  platforms TEXT[] DEFAULT '{}',
  mode TEXT NOT NULL DEFAULT 'copilot',          -- 'copilot' (方案A) | 'matrix_auto' (方案B)
  target_groups JSONB DEFAULT '[]'::jsonb,       -- Recommended groups/hashtags from AI radar
  copies JSONB DEFAULT '[]'::jsonb,              -- Anti-ban varied copies generated by AI
  dispatch_status TEXT DEFAULT 'draft',          -- 'draft' | 'queued' | 'publishing' | 'completed'
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_marketing_social_campaigns_user ON public.marketing_social_campaigns(user_id);

ALTER TABLE public.marketing_social_campaigns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own campaigns"
  ON public.marketing_social_campaigns
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 4. Social Matrix Action Logs (養號與發文歷程日誌)
CREATE TABLE IF NOT EXISTS public.marketing_social_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id UUID REFERENCES public.marketing_social_accounts(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,                     -- 'warmup_scroll' | 'warmup_like' | 'warmup_comment' | 'post_mode_a' | 'post_mode_b'
  details TEXT NOT NULL,
  status TEXT DEFAULT 'success',                 -- 'success' | 'warning' | 'failed'
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_marketing_social_logs_user ON public.marketing_social_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_social_logs_account ON public.marketing_social_logs(account_id);

ALTER TABLE public.marketing_social_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own social logs"
  ON public.marketing_social_logs
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
