name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_uvwqvGbN2NSTwAZb1i47XuC7
          VERCEL_PROJECT_ID: prj_WsVYwoxWAKh5OyqErjXz4lwagjOT
